### ISSUE TITLE
[Errno 19] No such device

### ISSUE THREAD

**Issue by oikos99** [jacklam718/http-request-capture#2]
Thank you Jack for making this awesome script.  I'm getting the following error.  Can you please help?  Thanks :)

`NING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
Wed, 27 Feb 2019 23:53:58 -0800: sniffing http requests on port 80 using network interface en0
Traceback (most recent call last):
  File "http_request_capture.py", line 57, in <module>
    filter='tcp and port {port}'.format(port=args.port),
  File "/home/paul/.local/lib/python3.6/site-packages/kamene/sendrecv.py", line 581, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/home/paul/.local/lib/python3.6/site-packages/kamene/arch/linux.py", line 472, in __init__
    self.ins.bind((iface, type))
OSError: [Errno 19] No such device
`

**Comment by samiti3d** [comment]
Did you run successfully?

**Comment by polymaxcube** [comment]
Have you  tried  `python3 http_request_capture.py --iface eth0 --port 80`
